export const USER_AUTH_QUESTIONS: string[] = [
    'Warum sind wir hier?',
    'Seit wann benutzt du diese App?',
    'Warum benutzt du diese App?',
    'Was war deine erste Lieblingsfarbe?',
    'Bist du mit deinem Job zufrieden?',
    'Welche Hobbys hast du und welche Hobbys hasst du?',
    'Macht dir Schule Spaß?',
    'Welchen Beruf wolltest du schon immer einmal ausüben?',
    'Wurdest du schonmal von Leuten hintergangen?',
    'Was ist dein Lieblingsanime/ -serie/ -film?',
    'Welche Stadt magst du am meisten?',
    'Wo ist dein Lieblingsort?',
    'Schaust du gerne Fernsehen?',
    'Was machen die Tiere im Zoo?',
    'Warum sind das so viele Fragen?',
    'Wer denkt sich so etwas aus?',
];
