name: Lint Check

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend # Alle Befehle standardmäßig im Frontend-Ordner ausführen

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22 with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Angular lint
        run: npm run lint
